name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  show-project-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show project name from pyproject.toml
        run: |
          python -c "import tomllib; print('📦 Project name:', tomllib.load(open('pyproject.toml', 'rb'))['project']['name'])"

  release-build:
    runs-on: ubuntu-latest
    needs: show-project-name  # 👈 等待项目名称检查完成
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
